In [1]:
import numpy as np
from tqdm import tqdm
import itertools as it
from pathlib import Path

INPUT = Path("day16/input.txt").read_text().strip()

def pattern(repeat):
    repeats = [[x] * repeat for x in (0, 1, 0, -1)]
    gen = it.cycle(it.chain(*repeats))
    next(gen)  # skip 1
    return gen

def pattern_matrix(n):
    return np.array([list(it.islice(pattern(i+1), n)) for i in range(n)])

def phase_at(x, n):
    x = np.array(list(x), dtype=np.int).reshape(1, -1)
    p = pattern_matrix(x.shape[1])
    for _ in tqdm(range(n)):
        r = np.abs((x * p).sum(axis=1))
        x = r - (r // 10) * 10
    return "".join(x.astype(str))

def phase_at(x, n):
    x = np.array(list(x), dtype=np.int)
    for _ in tqdm(range(n)):
        r = np.abs([
            sum(a * b for a, b in it.islice(zip(x, pattern(i+1)), i, None))
            for i in range(len(x))
        ])
        x = r - (r // 10) * 10
    return "".join(x.astype(str))

assert phase_at("80871224585914546619083218645595", 100)[:8] == "24176176"
assert phase_at("19617804207202209144916044189917", 100)[:8] == "73745418"
assert phase_at("69317163492948606335995924319873", 100)[:8] == "52432133"

100%|██████████| 100/100 [00:00<00:00, 3348.59it/s]


In [2]:
phase_at("80871224585914546619083218645595", 100)[:8]

100%|██████████| 100/100 [00:00<00:00, 1965.94it/s]


'24176176'

### Part 1

In [3]:
phase_at(INPUT, 100)[:8]

100%|██████████| 100/100 [00:07<00:00, 13.41it/s]


'15841929'

### Part 2

In [4]:
blob = INPUT * 10_000

In [5]:
%%time
p100 = phase_at(blob, 100)
p100[:8]

  0%|          | 0/100 [00:00<?, ?it/s]

KeyboardInterrupt: 

In [6]:
x = tuple(map(int, "12345678"))
x

(1, 2, 3, 4, 5, 6, 7, 8)

In [9]:
pattern_matrix(len(x))

array([[ 1,  0, -1,  0,  1,  0, -1,  0],
       [ 0,  1,  1,  0,  0, -1, -1,  0],
       [ 0,  0,  1,  1,  1,  0,  0,  0],
       [ 0,  0,  0,  1,  1,  1,  1,  0],
       [ 0,  0,  0,  0,  1,  1,  1,  1],
       [ 0,  0,  0,  0,  0,  1,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  1]])

In [8]:
pattern_matrix(len(x)*2)

array([[ 1,  0, -1,  0,  1,  0, -1,  0,  1,  0, -1,  0,  1,  0, -1,  0],
       [ 0,  1,  1,  0,  0, -1, -1,  0,  0,  1,  1,  0,  0, -1, -1,  0],
       [ 0,  0,  1,  1,  1,  0,  0,  0, -1, -1, -1,  0,  0,  0,  1,  1],
       [ 0,  0,  0,  1,  1,  1,  1,  0,  0,  0,  0, -1, -1, -1, -1,  0],
       [ 0,  0,  0,  0,  1,  1,  1,  1,  1,  0,  0,  0,  0,  0, -1, -1],
       [ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

In [14]:
n = 1
L = 4 * n
P = len(INPUT)

In [18]:
np.lcm(L, P)

1300

In [19]:
L, P

(4, 650)

In [20]:
L * P

2600

In [23]:
1300 // L, 1300 // P

(325, 2)

In [28]:
pattern_matrix(1300)[0, :] * np.array(list(INPUT * 2), dtype=int)

array([ 5,  0, -7, ...,  0, -7,  0])

In [37]:
zz = pattern_matrix(1300)[0, :] * np.array(list(INPUT * 2), dtype=int)
zz[:650]

array([ 5,  0, -7,  0,  9,  0, -7,  0,  1,  0,  0,  0,  9,  0, -1,  0,  4,
        0, -5,  0,  5,  0, -4,  0,  7,  0, -1,  0,  5,  0, -7,  0,  9,  0,
       -9,  0,  6,  0, -5,  0,  0,  0, -7,  0,  8,  0, -9,  0,  3,  0, -7,
        0,  8,  0,  0,  0,  4,  0, -8,  0,  3,  0, -9,  0,  4,  0, -2,  0,
        1,  0, -7,  0,  2,  0, -1,  0,  3,  0, -9,  0,  8,  0, -5,  0,  6,
        0, -3,  0,  1,  0, -3,  0,  5,  0, -9,  0,  1,  0, -9,  0,  3,  0,
       -4,  0,  8,  0, -4,  0,  7,  0, -7,  0,  4,  0, -1,  0,  5,  0, -3,
        0,  1,  0, -2,  0,  6,  0, -8,  0,  0,  0, -3,  0,  8,  0, -2,  0,
        5,  0, -9,  0,  4,  0, -6,  0,  3,  0, -2,  0,  1,  0, -4,  0,  1,
        0, -1,  0,  1,  0, -2,  0,  8,  0,  0,  0,  3,  0, -5,  0,  3,  0,
       -3,  0,  5,  0, -3,  0,  4,  0, -4,  0,  6,  0, -9,  0,  1,  0, -8,
        0,  9,  0, -9,  0,  8,  0, -6,  0,  3,  0, -5,  0,  1,  0,  0,  0,
        9,  0, -8,  0,  9,  0, -2,  0,  3,  0, -6,  0,  0,  0, -4,  0,  8,
        0, -5,  0,  2,  0

In [38]:
zz[650:]

array([-5,  0,  7,  0, -9,  0,  7,  0, -1,  0,  0,  0, -9,  0,  1,  0, -4,
        0,  5,  0, -5,  0,  4,  0, -7,  0,  1,  0, -5,  0,  7,  0, -9,  0,
        9,  0, -6,  0,  5,  0,  0,  0,  7,  0, -8,  0,  9,  0, -3,  0,  7,
        0, -8,  0,  0,  0, -4,  0,  8,  0, -3,  0,  9,  0, -4,  0,  2,  0,
       -1,  0,  7,  0, -2,  0,  1,  0, -3,  0,  9,  0, -8,  0,  5,  0, -6,
        0,  3,  0, -1,  0,  3,  0, -5,  0,  9,  0, -1,  0,  9,  0, -3,  0,
        4,  0, -8,  0,  4,  0, -7,  0,  7,  0, -4,  0,  1,  0, -5,  0,  3,
        0, -1,  0,  2,  0, -6,  0,  8,  0,  0,  0,  3,  0, -8,  0,  2,  0,
       -5,  0,  9,  0, -4,  0,  6,  0, -3,  0,  2,  0, -1,  0,  4,  0, -1,
        0,  1,  0, -1,  0,  2,  0, -8,  0,  0,  0, -3,  0,  5,  0, -3,  0,
        3,  0, -5,  0,  3,  0, -4,  0,  4,  0, -6,  0,  9,  0, -1,  0,  8,
        0, -9,  0,  9,  0, -8,  0,  6,  0, -3,  0,  5,  0, -1,  0,  0,  0,
       -9,  0,  8,  0, -9,  0,  2,  0, -3,  0,  6,  0,  0,  0,  4,  0, -8,
        0,  5,  0, -2,  0